[colors]

[colors.primary]
background = '#111c18'
foreground = '#C1C497'

[colors.normal]
black   = "#23372B"
red     = "#FF5345"
green   = "#549e6a"
yellow  = "#459451"
blue    = "#97CB98"
magenta = "#D2689C"
cyan    = "#2DD5B7"
white   = "#F6F5DD"

[colors.bright]
black   = "#53685B"
red     = "#db9f9c"
green   = "#72cfa3"
yellow  = "#D8C14C"
blue    = "#ACD4CF"
magenta = "#75bbb3"
cyan    = "#8CD3CB"
white   = "#9eebb3"

[colors.cursor]
text   = "#000000"
cursor = "#D7C995"
